---
- name: Install Docker and Java on all EC2 instances
  hosts: ec2-nodes
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Java (OpenJDK 17)
      apt:
        name: openjdk-17-jdk
        state: present
